filebeat:
  inputs:
    - type: log
      paths:
        - /var/log/vault/*.log
        - /var/log/*.log
      tags: [vault]

  processors:
     - drop_fields:
       fields: ["host"]
#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["logstash.{{ env }}.fewknow.net:5044"]
