---
- name: Download Vault binary check (sha256)
  get_url:
    url: https://releases.hashicorp.com/vault/{{ vault.version }}/vault_{{ vault.version }}_linux_amd64.zip
    dest: /tmp/vault.zip
    checksum: "sha256:{{ vault.checksum }}"

- name: Install Vault
  unarchive:
    src: /tmp/vault.zip
    dest: "{{ vault.deploy_dir }}"
    copy: no

- name: Create Vault configuration directory
  file:
    state: directory
    path: "{{ vault.config_dir }}"
    mode: 0650

- name: Copy Vault configuration file as .tmp
  copy:
    src: vault.conf.tmp
    dest: "{{ vault.config_dir }}"

- name: Create vault group
  group:
    name: vault
    state: present

- name: Create vault user
  user:
    name: vault
    group: vault
    groups: root
    comment: User for vault service

- name: Copy vault servie script
  template:
    src: "{{ item.source }}"
    dest: "{{ item.destination }}"
  with_items:
    - { source: roles/vault/files/vault.service, destination: /etc/systemd/system }
