- name: "Download python {{ python_version }}"
  get_url:
    url: https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz
    dest: /tmp
    mode: 0755
    validate_certs: false

- name: "Unarchive python-{{ python_version }}"
  shell: tar -xvf /tmp/Python-{{ python_version }}.tgz -C /tmp

- name: Build Python
  shell: |
    cd /tmp/Python-{{ python_version }}
    ./configure
    make
    sudo checkinstall

- name: Download pip 8.1
  get_url:
    url: https://pypi.python.org/packages/e7/a8/7556133689add8d1a54c0b14aeff0acb03c64707ce100ecd53934da1aa13/pip-8.1.2.tar.gz#md5=87083c0b9867963b29f7aba3613e8f4a
    dest: /tmp
    validate_certs: false

- name: "Unarchive pip-8.1.2.tar.gz"
  shell: tar -xvf /tmp/pip-8.1.2.tar.gz -C /tmp

- name: Install pip
  shell: |
    cd /tmp/pip-8.1.2
    python setup.py install

- name: Install Python packages
  pip:
    name: "{{ item }}"
  with_items: "{{ pip.install }}"
