- name: Download and Install Hashicorp Packer
  get_url:
    url: https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip?_ga=2.218993181.525810411.1517337525-1019068480.1517337525
    dest: /usr/bin/packer
    
