---
- name: Install packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - apt-transport-https
    - software-properties-common

- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: present
