---
- file:
    path: /opt/mule/
    owner: mule
    group: mule
    # when specifying mode using octal numbers, add a leading 0
    mode: 0777
    recurse: yes

- file:
    path: /etc/systemd/system/mule.service
    owner: root
    group: root
    # when specifying mode using octal numbers, add a leading 0
    mode: 0644
