---
  - name: create mule group
    group:
      name: mule
      state: present

  - name: Create mule user
    user:
      name: mule
      group: mule
      groups: root,syslog
      append: yes
      state: present
      shell: /bin/bash
      system: no
      createhome: yes
      home: /home/mule
      comment: user for mule service
